"""edited the model to fix error

Revision ID: 5a61a0f1cc46
Revises: e45b5bad13f3
Create Date: 2025-03-02 21:51:20.965889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a61a0f1cc46'
down_revision = 'e45b5bad13f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('plaid_access_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plaid_access_token', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
