name: One Bank CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./Backend
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - run: pip install -r requirements.txt
        - run: python -m pytest || echo "No tests found, continuing workflow"

  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./onebank-frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run lint
      - run: npm run test -- --watchAll=false

  deploy-backend:
    name: Deploy Flask Backend to Render
    needs: [backend-test]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy on Render
        run: |
          curl -X POST ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}

  deploy-frontend:
    name: Deploy React Frontend to Render
    needs: [frontend-test]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy on Render
        run: |
          curl -X POST ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}
